# Generated by Django 4.0 on 2021-12-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('Description', models.CharField(default='', max_length=450)),
                ('image', models.ImageField(upload_to='upload/products/')),
                ('product_type', models.CharField(max_length=60)),
                ('Category', models.ForeignKey(default='Uwal', on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
