# Generated by Django 4.0 on 2022-01-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='saic_logo.png', upload_to='upload/products/'),
        ),
    ]
