# Generated by Django 4.0 on 2022-01-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='kunal.jpg', upload_to='upload/products/'),
        ),
    ]
