# Generated by Django 4.0 on 2022-01-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='upload/products/kunal.jpg', upload_to='upload/products2/'),
        ),
    ]
