# Generated by Django 4.0 on 2022-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='upload/products/kunal.jpg', upload_to='upload/products3/'),
        ),
    ]
